export const AI_SETTINGS = {
  GROQ: {
    TRANSLATION_TEMPERATURE: 0.3,
    TRANSCRIPTION_TEMPERATURE: 0.1
  },
  GEMINI: {
    TRANSLATION_TEMPERATURE: 0.3,
    TRANSCRIPTION_TEMPERATURE: 0.1
  }
} as const;